### ISSUE TITLE
a post request example with ansible

### ISSUE THREAD

**Issue by thiagogomesverissimo** [thiagogomesverissimo/thiagogomesverissimo.github.io#18]
```
deploy_ojs_query:
  - adminUsername={{deploy_ojs_user}}
  - adminPassword={{deploy_ojs_password}}
  - adminPassword2={{deploy_ojs_password}}
  - adminEmail={{deploy_ojs_email}}
  - locale={{deploy_ojs_locale}}
  - additionalLocales[]={{deploy_ojs_locale}}
  - clientCharset=utf-8
  - connectionCharset=utf8
  - databaseCharset=utf8
  - filesDir={{ deploy_ojs_files | replace('/', '%2f') }}
  - encryption=sha1
  - databaseDriver={{deploy_ojs_database.driver}}
  - databaseHost={{deploy_ojs_database.host}}
  - databaseUsername={{deploy_ojs_database.username}}
  - databasePassword={{deploy_ojs_database.password}}
  - databaseName={{deploy_ojs_database.name}}
  - oaiRepositoryId=ojs.{{ deploy_ojs_url }}
```
Task:
```
- name: new installation
  uri:
    url: "{{ deploy_ojs_protocol }}://{{ deploy_ojs_url }}/index.php/index/install/install"
    method: POST
    body_format: raw
    body: "{{ deploy_ojs_query | join('&') }}"
    status_code: 200
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  when: deploy_ojs_new_installation
  tags:
    - ojs
```
